version: "3.8"

services:

  app:
    build: ./core
    env_file:
      - .env
    volumes:
      - media:/app/media/
      - static:/app/static_dir/

  nginx:
    build: ./nginx
    ports:
      - "8000:80"
    volumes:
      - media:/media/
      - static:/static/
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: redis

  celery:
    image: celery
    restart: always
    build: ./core
    env_file:
      - .env
    command: celery -A core worker -l INFO
    depends_on:
      - redis
      - app

volumes:
  static:
  media: