# Generated by Django 4.2.11 on 2024-03-21 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("group_incomes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collect",
            name="payments",
        ),
        migrations.AddField(
            model_name="payment",
            name="collect",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="group_incomes.collect",
                verbose_name="Платежи",
            ),
            preserve_default=False,
        ),
    ]
