# Generated by Django 4.2.11 on 2024-03-21 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("group_incomes", "0002_remove_collect_payments_payment_collect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Донатер",
            ),
        ),
    ]
