# Generated by Django 4.2.11 on 2024-04-11 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("group_incomes", "0004_alter_collect_required_amount_alter_payment_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collect",
            options={
                "default_related_name": "collects",
                "verbose_name": "Сбор",
                "verbose_name_plural": "Сборы",
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={
                "default_related_name": "payments",
                "verbose_name": "Донат",
                "verbose_name_plural": "Донаты",
            },
        ),
        migrations.AlterField(
            model_name="collect",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="collect",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="group_incomes.event",
                verbose_name="Событие",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
    ]
