# Generated by Django 4.2.11 on 2024-05-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("group_incomes", "0006_delete_collectpayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="collect",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="group_incomes.collect",
                verbose_name="Платежи",
            ),
        ),
    ]
